#!/usr/bin/env bash

# collectionchecksum
# This script will create checksums of metadata files, concatenate checksum.md5
# files, and append to one large checksum file for each directory. This script
# presumes a highly specific directory structure based on CUNY TV's Archival
# Information Package directory structure.

SCRIPTDIR="$(dirname "${0}")"
. "${SCRIPTDIR}/ltoperfunctions" || { echo "Missing '${SCRIPTDIR}/ltoperfunctions'. Exiting." ; exit 1 ; }

while [ "${*}" != "" ] ; do
    INPUT="${1}"
    TAPECHECKSUMFILE="${INPUT}/tapechecksum.md5"
    if [ -f "${TAPECHECKSUMFILE}" ] ; then
        _report -wt "A collection checksum already exists at ${TAPECHECKSUMFILE}"
        exit 1
    fi
    TEMPCHECKSUMFILE="$(_maketemp)"
    cd "${INPUT}"

    #loop through the directories, find the checksum files, cat them together, and also sed to add the media ids
    while read CHECKSUMFILES ; do
        PACKAGE="$(basename "$(dirname "$(dirname "${CHECKSUMFILES}")")")"
        _report -d "Concatenating ${CHECKSUMFILES}."
        cat "${CHECKSUMFILES}" | sed "s|  ./|  ./${PACKAGE}/objects/|g" >> "${TEMPCHECKSUMFILE}"
    done < <(find "${INPUT}" -maxdepth 3 -mindepth 3 -type f -iname "checksum.md5")

    #create md5 checksums for all of the files in the metadata directory
    _report -d "Creating checksums for all metadata directories."
    md5deep -rel ./*/metadata >> "${TEMPCHECKSUMFILE}"

    _report -d "Sorting and saving ${TAPECHECKSUMFILE}."
    sort -k2 "${TEMPCHECKSUMFILE}" | grep -v .DS_Store >> "${TAPECHECKSUMFILE}"

    shift
done
