#!/usr/bin/env bash

# formatlto
# Formats an LTO tape with LTFS.

SCRIPTDIR=$(dirname "${0}")
DEPENDENCIES=(mkltfs mmfunctions)
TAPE_SERIAL_REGEX="^[A-Z0-9]{6}(L[567])?$"
BLUE="$(tput setaf 4)"  # Blue     - For Questions
NC="$(tput sgr0)"       # No Color

. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ; }

if [[ $(dirname $(which "${0}")) = "/usr/local/bin" || $(dirname $(which "${0}")) = "${HOME}/.linuxbrew/bin" ]] ; then
    VERSION=$(TMP=$(brew info ltopers | grep -Eo "/ltopers/.* \(") ; echo ${TMP:9:(${#TMP}-11)})
else
    VERSION=""
fi

_usage(){
    cat <<EOF
$(basename "${0}") ${VERSION}
This script formats an LTO tape with LTFS.
Dependencies: ${DEPENDENCIES[@]}

Usage: $(basename "${0}") [-f] [-c] | -h
  -f  force formatting
  -c  use compression
  -h  display this help
EOF
}

unset MIDDLE_OPTIONS
while getopts ":fch" opt ; do
    case "${opt}" in
        f) FORCE=1 ;;
        c) COMPRESS=1 ;;
        h) _usage ; exit 0 ;;
        *) _report -w "Error: Bad option -${OPTARG}" ; _usage ; exit 1 ;;
    esac
done

if [ "${FORCE}" = "1" ] ; then
    MIDDLE_OPTIONS+=(-f)
    _report -d "Will force formatting."
fi

if [ ! "${COMPRESS}" = "1" ] ; then
    MIDDLE_OPTIONS+=(-c)
else
    _report -d "Will use compression."
fi

if [ ! "${LTO_ARRAY}" ] ; then
    if [[ "$(uname -s)" = "Darwin" ]] ; then
        # try to figure out how many LTO decks are attached
        LTO_ARRAY=($(system_profiler SPSASDataType | grep "SCSI Target Identifier" | cut -d : -f2 | sort | xargs))
    else
        #### TO DO: itemize when there are multiple LTO drives in Linux and Windows
        LTO_ARRAY=(0)
    fi
fi

if [[ "${#LTO_ARRAY[@]}" -gt 1 ]] ; then
   PS3="${BLUE}Which LTO deck?${NC} "
   eval set "${LTO_ARRAY[@]}"
   select DECK in "$@"
   do
       break
   done
   if [ ! "${DECK}" ] ; then
       _report -w "Error: You selected an invalid deck."
       exit 1
   fi
else
   #### TO DO: select the correct path to the drive on Linux and Windows
   if [[ "$(uname -s)" = "Linux" ]] ; then
       DECK='/dev/sg3'
   else
       DECK=0
   fi
fi

_report -qn "Enter the tape identifier: "
read TAPE_ID
if [[ ! $(echo "${TAPE_ID}" | grep -E "${TAPE_SERIAL_REGEX}") ]] ; then
   _report -w "Error: The tape id must be exactly 6 capital letters and/or numbers, possibly followed by 'L5', 'L6' or 'L7' specifying the LTO generation."
   exit 1
fi
if [[ $(which ltfs_ldun) ]] ; then
    ltfs_ldun load "${DECK}"
fi
mkltfs ${MIDDLE_OPTIONS[@]} --device=${DECK} --tape-serial="${TAPE_ID}" --volume-name="${TAPE_ID}"
if [[ $(which ltfs_ldun) ]] ; then
    ltfs_ldun unload "${DECK}"
fi
