.TH ltopers 1 "https://github.com/amiaopensource/ltopers" "2019\-01\-18" "AMIA Open Source"
.\" Turn off justification for nroff.
.if n .ad l
.\" Turn off hyphenation.
.nh
.SH NAME
LTOpers \- Bash scripts to manage LTO cartridges with LTFS
.SH SYNOPSIS
.SS
\fBformatlto\fR [\fB\-f\fR] [\fB\-c\fR] [\fB\-x\fR] | \fB\-h\fR
Format an LTO cartridge with LTFS.
.TP 4
.B \-f
force formatting
.TP
.B \-c
use compression
.TP
.B \-x
use barcode label as tape serial (caveat: this is \fBNOT\fR standard)
.TP
.B \-h
display a help message
.SS 
.B ltopers
Display this man.
.SS
.B mountlto
Mount an LTO cartridge.
.SS
\fBreadlto \-t \fIserial\fR [\fB\-e \fIY\fR|\fIN\fR] | \fB\-h\fR
Transfer files from an LTO cartridge to another location.
.TP 4
.B \-t
cartridge's \fIserial
.TP
.B \-e
eject the cartridge after migration: \fIY\fR (default) or \fIN
.TP
.B \-x
use barcode label as tape serial (caveat: this is \fBNOT\fR standard)
.TP
.B \-h
display a help message
.SS
\fBrenameschemas \-u\fR | \fB\-h\fR
Find all .schema LTFS indexes in the LTO_LOGS directory and rename them to use the top\-level file system directory name rather than the UUID. Any conflicting filenames are moved to another folder, if needed.
.TP 4
.B \-u
change dir-named schema files to the tape UUID
.TP
.B \-h
display a help message
.SS
\fBverifylto \-t \fIserial\fR [\fB\-e \fIY\fR|\fIN\fR] | \fB\-h\fR
Verify the checksums of an LTO cartridge.
.TP 4
.B \-t
cartridge's \fIserial
.TP
.B \-e
eject the cartridge after migration: \fIY\fR (default) or \fIN
.TP
.B \-x
use barcode label as tape serial (caveat: this is \fBNOT\fR standard)
.TP
.B \-h
display a help message
.SS
\fBwritelto \-t \fIserial\fR [\fB\-e \fIY\fR|\fIN\fR] [\fB\-v\fR] | \fB\-h\fR
Write the contents of a specified directory onto a mounted LTFS\-formatted LTO cartridge.
.TP 4
.B \-t
cartridge's \fIserial
.TP
.B \-e
eject the cartridge after migration: \fIY\fR (default) or \fIN
.TP
.B \-v
verify the checksums of the LTO cartridge's contents
.TP
.B \-x
use barcode label as tape serial (caveat: this is \fBNOT\fR standard)
.TP
.B \-h
display a help message
.SH DATABASE-RELATED COMMANDS
.SS
.B ingestcollectionchecksum
Import already existing information to the database (read back checksums). It can be run either on individual files or on directories containing multiple files.
.SS
.B ingestschemas
Import already existing information to the database (LTO schema information). It can be run either on individual files or on directories containing multiple files.
.SS
\fBsearchlto\fR [\fB\-c\fR] [\fB\-f\fR] [\fB\-m\fR] {\fIquery\fR} | \fB\-h\fR
Perform at least one \fIquery\fR against the LTO schema information stored in the database.
.TP 4
.B \-c
compare input to database
.TP
.B \-f
show full results (as opposed to only .mov files)
.TP
.B \-m
MD5 checksums
.TP
.B \-h
display a help message
.SH CUNY-SPECIFIC COMMANDS
.SS
.B collectionchecksum
Create checksums of metadata files, concatenate checksum.md5 files, and append to one large checksum file for each directory.
.SS
\fBindexschemas \-t\fR | \fB\-h\fR
Make a text file listing certain files from the LTFS schema file.
.TP 4
.B \-t
check schema files modified today for volume names that may need to be overwritten
.TP
.B \-h
display a help message
.SH COPYRIGHT
Copyright (c) 2014\-2019 by AMIA Open Source
.SH LICENSE
The LTOpers package is licensed under an MIT License.
.SH DISCLAIMER
The LTOpers package is provided "as is" without warranty or support of any kind.
