.TH ltopers 1 "https://github.com/amiaopensource/ltopers" "2017\-06\-02" "AMIA Open Source"
.SH NAME
LTOpers - Scripts to manage LTO cartridges with LTFS
.SH SYNOPSIS
.SS formatlto [-f] [-c] | -h
Format an LTO cartridge with LTFS.
.TP
.B -f
force formatting
.TP
.B -c
use compression
.TP
.B -h
display a help message
.SS ltopers
Display this man.
.SS mountlto
Mount an LTO cartridge.
.SS readlto -t \fIserial\fB [-e \fIY\fR|\fIN\fB] | -h
Transfer files from an LTO cartridge to another location.
.TP
.B -t
cartridge's \fIserial
.TP
.B -e
eject the cartridge after migration: \fIY\fR (default) or \fIN
.TP
.B -h
display a help message
.SS renameschemas  -u | -h
.TP
.B -u
change dir-named schema files to the tape uuid
.TP
.B -h
display a help message
.SS verifylto -t \fIserial\fB [-e \fIY\fR|\fIN\fB] | -h
Verify the checksums of an LTO cartridge.
.TP
.B -t
cartridge's \fIserial
.TP
.B -e
eject the cartridge after migration: \fIY\fR (default) or \fIN
.TP
.B -h
display a help message
.SS writelto -t \fIserial\fB [-e \fIY\fR|\fIN\fB] [-v] | -h
Write the contents of a specified directory onto a mounted LTFS-formatted LTO cartridge.
.TP
.B -t
cartridge's \fIserial
.TP
.B -e
eject the cartridge after migration: \fIY\fR (default) or \fIN
.TP
.B -v
verify the checksums of the LTO cartridge's contents
.TP
.B -h
display a help message
.SH DATABASE-RELATED COMMANDS
.SS ingestcollectionchecksum
.SS ingestschemas
.SS searchlto
.SH CUNY-SPECIFIC COMMANDS
.SS collectionchecksum
Create checksums of metadata files, concatenate checksum.md5 files, and append to one large checksum file for each directory.
.SS indexschemas -t | -h
Make a text file listing certain files from the LTFS schema file.
.TP
.B -t
check schema files modified today for volume names that may need to be overwritten
.TP
.B -h
display a help message
.SH LICENSE
The LTOpers package is licensed under a Creative Commons Attribution 4.0 International License.
