#!/usr/bin/env bash
SCRIPTDIR=$(dirname $(which "${0}"))
. "${SCRIPTDIR}/mmfunctions"

_usage(){
    echo "yeah"
}

_compare_file(){
    if [ -f "${INPUT}" ] ; then
        DATE=$(date -u -r "$INPUT" +%Y-%m-%dT%H:%M:%S.0000000000Z)
        SIZE=$(wc -c "${INPUT}")
        echo "Information from Schema"
        mysql --login-path="${PREMIS_PROFILE}" "${PREMIS_NAME}" -B -e "SELECT modifyTime,fileSize,fileName FROM ltoSchema WHERE fileName LIKE '%${FILE_NAME}%'"
        echo "Information From File"
        echo "$DATE $SIZE"
    else
        echo "Input is not a valid file. Exiting"
        exit 1
    fi
}

OPTIND=1
while getopts ":hc" OPT; do
    case "${OPT}" in
        h) _usage ;;
        c) RUNMODE="compare" ;;
        *) echo "bad option -${OPTARG}" ; _usage ;
exit 1 ;;
    esac
done

shift $(( ${OPTIND} - 1 ))

while [ "${*}" != "" ] ; do
    INPUT="${1}"
    shift
    FILE_NAME=$(basename "${INPUT}")
    if [ "${RUNMODE}" = "compare" ] ; then
        _compare_file
    else
        mysql --login-path="${PREMIS_PROFILE}" "${PREMIS_NAME}" -B -e "SELECT ltoID,filePath FROM ltoSchema WHERE Concat(ltoID, '',filePath, '') LIKE '%${FILE_NAME}%'"
    fi
done

