#!/usr/bin/env bash
SCRIPTDIR=$(dirname $(which "${0}"))
. "${SCRIPTDIR}/mmfunctions"

_usage(){
    echo "yeah"
}

_compare_file(){
    if [ -f "${INPUT}" ] ; then
        DATE=$(date -u -r "$INPUT" +%Y-%m-%dT%H:%M:%S.000000000Z)
        SIZE=$(wc -c "${INPUT}")
        SQL_RESULTS=$(mysql --login-path="${PREMIS_PROFILE}" "${PREMIS_NAME}" -B -e "SELECT modifyTime,fileSize,fileName FROM ltoSchema WHERE fileName LIKE '%${SEARCH_TERM}%'")
        LTO_SIZE=$(echo ${SQL_RESULTS} | cut -d ' ' -f5)
        LTO_DATE=$(echo ${SQL_RESULTS} | cut -d ' ' -f4)
        
        if [ "${DATE}" != "${LTO_DATE}" ] ; then
            echo -e "\033[1;31mWARNING: Date mismatch between file data and file records in LTO database\033[0m"
        fi
        if [ $(echo "${SIZE}" | sed -e 's/^[[:space:]]*//' | cut -d' ' -f1) != "${LTO_SIZE}" ] ; then
            echo -e "\033[1;31mWARNING: Size mismatch between file data and file records in LTO database\033[0m"
        fi
        if [ "${DATE}" = "${LTO_DATE}" ] && [ $(echo "${SIZE}" | sed -e 's/^[[:space:]]*//' | cut -d' ' -f1) = "${LTO_SIZE}" ] ; then
            echo -e "\033[1;92mMatching File(s) Found\033[0m"
        fi
        if [ -n "${SQL_RESULTS}" ] ; then
            echo "Information from Schema"
            echo "------"
            echo "${SQL_RESULTS}"
            echo ""
            echo "Information From File"
            echo "------"
            echo "${DATE} ${SIZE}"            
        else
            echo "File with that name not found.  Checking for files of similar size and modification date"
            SQL_RESULTS=$(mysql --login-path="${PREMIS_PROFILE}" "${PREMIS_NAME}" -B -e "SELECT modifyTime,fileSize,fileName FROM ltoSchema WHERE fileSize='${SIZE}' OR modifyTime='${TIME}'")
            echo "Following possible matches were found:"
            echo "${SQL_RESULTS}"
            echo "Information from file"
            echo "${DATE} ${SIZE}"
        fi
            
    else
        echo "Input is not a valid file. Exiting"
        exit 1
    fi
}

OPTIND=1
while getopts ":hc" OPT; do
    case "${OPT}" in
        h) _usage ;;
        c) RUNMODE="compare" ;;
        *) echo "bad option -${OPTARG}" ; _usage ;
exit 1 ;;
    esac
done

shift $(( ${OPTIND} - 1 ))

while [ "${*}" != "" ] ; do
    INPUT="${1}"
    shift
    SEARCH_TERM=$(basename "${INPUT}")
    if [ "${RUNMODE}" = "compare" ] ; then
        _compare_file
    else
        mysql --login-path="${PREMIS_PROFILE}" "${PREMIS_NAME}" -B -e "SELECT ltoID,filePath FROM ltoSchema WHERE Concat(ltoID, '',filePath, '') LIKE '%${SEARCH_TERM}%'"
    fi
done

