#!/usr/bin/env bash

#migratelto 
#This script transfers files from an LTO tape. Script uses gcp. 

SCRIPTDIR=$(dirname "${0}")
TAPE_MOUNT_POINT="/Volumes"
TAPE_SERIAL_REGEX="^[A-Z0-9]{6}(L[567])?$"
TAPE_EJECT="Y"

. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ; }

_usage(){
    echo 
    echo "This script moves files from an lto tape to another location."
    echo "Usage: $(basename "${0}") -t [-e]"
    echo "  -e  state yes (Y) or no (N) to ejecting the tape after migration, default"
    echo "      is yes"
    echo
}

OPTIND=1
while getopts ":t:e" opt ; do
    case "${opt}" in
        t) TAPE_SERIAL="${OPTARG}" ;;
        e) TAPE_EJECT="${OPTARG}" ;;
        :) echo "Option -${OPTARG} requires an argument" ; exit 1 ;;
        *) echo "Bad option -${OPTARG}" ; _usage ; exit 1 ;;
    esac
done
shift $(( ${OPTIND} - 1 ))

TARGET="${1}"
if [[ ! $(echo "${TAPE_SERIAL}" | grep -E "${TAPE_SERIAL_REGEX}") ]] ; then
    echo "${TAPE_SERIAL} is not valid. The tape id must be exactly 6 capital letters and/or numbers, possibly followed by 'L5', 'L6' or 'L7' specifying the LTO generation."
    _usage
fi

TAPE_PATH="${TAPE_MOUNT_POINT}/${TAPE_SERIAL}"
_checkdir "${TAPE_PATH}"
_checkdir "${TARGET}"

gcp --preserve=mode,timestamps -nRv "${TAPE_PATH}/"* "${TARGET}/"

case "${TAPE_EJECT}" in
    y|Y) umount "${TAPE_PATH}" ;;
    *)   echo "Done migrating but not ejecting ${TAPE_SERIAL}." ;;
esac

