#!/usr/bin/env bash

# readlto 
# This script transfers files from an LTO tape to another location. 

VERSION=$(ls /usr/local/Cellar/ltopers/ | sort -n | tail -n 1)
SCRIPTDIR=$(dirname "${0}")
DEPENDENCIES=(gcp)
TAPE_MOUNT_POINT="/Volumes"
TAPE_SERIAL_REGEX="^[A-Z0-9]{6}(L[567])?$"
TAPE_EJECT="Y"

. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ; }

_usage(){
    cat <<EOF
$(basename "${0}") ${VERSION} 
This script moves files from an LTO tape to another location.
Usage: $(basename "${0}") -t [-e]
  -t  tape serial number
  -e  state yes (Y) or no (N) to ejecting the tape after migration, default
      is yes
EOF
}

OPTIND=1
while getopts ":t:e" opt ; do
    case "${opt}" in
        t) TAPE_SERIAL="${OPTARG}" ;;
        e) TAPE_EJECT="${OPTARG}" ;;
        :) echo "Option -${OPTARG} requires an argument" ; exit 1 ;;
        *) echo "Bad option -${OPTARG}" ; _usage ; exit 1 ;;
    esac
done
shift $(( ${OPTIND} - 1 ))

TARGET="${1}"
if [[ ! $(echo "${TAPE_SERIAL}" | grep -E "${TAPE_SERIAL_REGEX}") ]] ; then
    echo "${TAPE_SERIAL} is not valid. The tape id must be exactly 6 capital letters and/or numbers, possibly followed by 'L5', 'L6' or 'L7' specifying the LTO generation."
    _usage
fi

TAPE_PATH="${TAPE_MOUNT_POINT}/${TAPE_SERIAL}"
_checkdir "${TAPE_PATH}"
_checkdir "${TARGET}"

gcp --preserve=mode,timestamps -nRv "${TAPE_PATH}/"* "${TARGET}/"

case "${TAPE_EJECT}" in
    y|Y) umount "${TAPE_PATH}" ;;
    *)   echo "Done migrating but not ejecting ${TAPE_SERIAL}." ;;
esac

